### ISSUE TITLE
notification time is not displayed

### ISSUE THREAD

**Issue by TitanNano** [mutebg/pwa-weather#1]
I set the notification time to 7 am but the button still shows 8:00.

**Comment by mutebg** [comment]
Hi @TitanNano,
can you tell me your browser and operation system?
Thanks for the bug report

**Comment by TitanNano** [comment]
Android 7.1
Firefox Nighty 58.0a1

**Comment by mutebg** [comment]
Seems Firefox doesn't trigger onChange event when user select a date from input[type=date]. WIll investigate more and fix it soon :)

**Comment by TitanNano** [comment]
do you store this somewhere? Also when I reload the app I get 8:00.

**Comment by mutebg** [comment]
it's stored in index db. ( didn't save because onChange event didn't work correctly on FF )
I managed to fix the bug and also migrate the website to a  new hosting
Here is preview: https://willraintoday-64e72.firebaseapp.com/ 
I am doing final checks before domains redirect to it
