### ISSUE TITLE
API

### ISSUE THREAD

**Issue by rustan-id** [mutebg/pwa-weather#10]
Thanks for this project. It's really help to learn preact js. Would you like to share the api source (https://us-central1-willraintoday-64e72.cloudfunctions.net/api/). Thanks

**Comment by mutebg** [comment]
Hi @rustan-id 
the API source is placed in a function folder https://github.com/mutebg/pwa-weather/tree/master/functions 
It uses firebase cloud functions

**Comment by rustan-id** [comment]
Thanks. Sorry for my poor.
